update sbt-idea-plugin to 5.0.5
It contains the change:
when constructing a test classpath, move the plugins classpath before system classpath to better emulate production behavior

We observed exception
```
java.lang.ClassCastException: class k.k.k.k.w cannot be cast to class com.intellij.openapi.startup.StartupActivity (k.k.k.k.w and com.intellij.openapi.startup.StartupActivity are in unnamed module of loader com.intellij.util.lang.PathClassLoader @70177ecd)
```
after IntelliJ IDEA update

Turns out this was caused by a class clash between scrambled jars ultimate-plugin.jar and product.jar.

The fix corresponds to how it's done in IntelliJ Platform Gradle Plugin, though we still have some differences.

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/main/src/main/kotlin/org/jetbrains/intellij/platform/gradle/tasks/TestIdeTask.kt


(cherry picked from commit 9586aec643646a71665fd90f4c353b14160d5a11)