[decompiler] fix decompile action, use the virtual path as string instead of a nio path #SCL-23447 fixed
The path kept in VirtualFile is actually not a path but rather a URI.
When we used java.io.File API it worked because File could reference to an invalid path. However after migration to java.nio.file.Path api (#SCL-23339) toNioPath can throw an exception. This can happen if the URI references to the file inside a jar file.

Exception text:
```
java.lang.UnsupportedOperationException: Failed to map jar:///Users/dmitrii.naumenko/.sbt/boot/scala-2.12.20/org.scala-sbt/sbt/1.10.7/main_2.12-1.10.7.jar!/sbt/Project.class (filesystem com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl@72da37b0) into nio Path
	at com.intellij.openapi.vfs.VirtualFile.toNioPath(VirtualFile.java:165)
	at org.jetbrains.plugins.scala.decompileToJava.ScalaDecompilerServiceImpl$$anonfun$mappingsForClassfile$1.applyOrElse(ScalaDecompilerServiceImpl.scala:55)
```